"""Local stdio MCP server exposing the curated knowledge tools.

Two tools — nap and milestone. (Play activities are GENERATED by the agent from the
milestones this server returns, not served as a tool — see docs/DECISIONS.md. So this
server is intentionally 2 tools, not 3; CONTRIBUTING.md's "3 tools" predates that decision.)

Transport: stdio. No network endpoint, no inbound access. Bundled inside the agent's
container; the agent spawns this as a subprocess and talks MCP over stdin/stdout.

The deterministic lookups live in tools/ + loader.py. This file only does the protocol
layer: it registers those functions as MCP tools and runs the stdio loop. The tool
DESCRIPTIONS below are load-bearing — they tell the model it must call the tool rather
than answer a developmental fact from memory (the anti-hallucination contract, brief sec 7).

Verified against mcp (FastMCP) 1.28.0:  FastMCP(name) -> @mcp.tool(description=...) -> mcp.run("stdio").
"""
from mcp.server.fastmcp import FastMCP

from .tools.naps import get_nap_guidance as _get_nap_guidance
from .tools.milestones import get_milestone_checkin as _get_milestone_checkin

mcp = FastMCP("mom-day-organiser-knowledge")

_NAP_DESC = (
    "Get TYPICAL nap/sleep guidance for a baby of a given age, as a curated band with its "
    "source and evidence tier. Call this WHENEVER you need a nap count, daytime-sleep "
    "duration, total sleep, or nap-transition fact. You MUST NOT answer these numbers from "
    "your own knowledge — use ONLY the values this returns, and phrase them as typical "
    "ranges, never as targets. Input is age_months (integer) ONLY; never pass personal data. "
    "If the age is out of range the result says so — do not guess a number."
)

_MILESTONE_DESC = (
    "Get the TYPICAL developmental milestones for a baby of a given age, grouped by domain "
    "(gross motor, fine motor, self-help, problem-solving, social/emotional, receptive and "
    "expressive language), as a curated band with its source and tier. Call this WHENEVER you "
    "need to know what a baby is typically working toward — including as the grounded input "
    "for generating play activities (you invent the games; the milestones they target come "
    "from HERE, never from your own memory). Phrase milestones as typical, not prescriptive. "
    "Input is age_months (integer) ONLY; never pass personal data. Out-of-range results say "
    "so — do not guess."
)


@mcp.tool(description=_NAP_DESC)
def get_nap_guidance(age_months: int) -> dict:
    return _get_nap_guidance(age_months)


@mcp.tool(description=_MILESTONE_DESC)
def get_milestone_checkin(age_months: int) -> dict:
    return _get_milestone_checkin(age_months)


def main() -> None:
    """Run the MCP server over stdio (the agent spawns this as a subprocess)."""
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
