"""The ONE agent: an ADK LlmAgent that consumes the local stdio MCP server via McpToolset.

Arc 2 — the wiring. A REAL LlmAgent + a REAL McpToolset pointed at mcp_server/server.py, so
the MODEL (not a hardcoded sequence) decides when to call get_nap_guidance /
get_milestone_checkin. Importing ADK without instantiating it (the NutriGuard mistake) does not
count: build_agent() returns a live agent, and list_mcp_tools() proves the server's two tools
are actually exposed to it.

Two tools, not three — play is generated by the agent from the milestones, not served as a tool
(docs/DECISIONS.md).

Facts discipline lives in the system prompt (agent/instructions.py, OWNED BY SUJATHA — imported
here, never edited here). Personal data never leaves the device: only age_months goes to a tool.

Verified against google-adk 2.3.0 + mcp 1.28.0:
  LlmAgent(name=, model=, instruction=, tools=[McpToolset(...)])
  McpToolset(connection_params=StdioConnectionParams(server_params=StdioServerParameters(...)))
  await toolset.get_tools()  # spawns the server, lists tools — no model call, no API key
"""
import os
from pathlib import Path

from google.adk.agents import LlmAgent
from google.adk.tools.mcp_tool import McpToolset, StdioConnectionParams
from mcp import StdioServerParameters

from .instructions import SYSTEM_INSTRUCTION

REPO_ROOT = Path(__file__).resolve().parent.parent

# Model is env-switchable via ADK_MODEL. Gemini via Google AI Studio is the DEFAULT (and the
# documented submission model). Models rotate: gemini-2.0-flash was RETIRED 2026-03-03, so the
# current free-tier default is gemini-2.5-flash (or gemini-2.5-flash-lite). Check the live
# free-tier list if this 429s with "limit: 0": https://ai.google.dev/gemini-api/docs/rate-limits
#
# To test on another provider (e.g. DeepSeek, to dodge Gemini's free-tier daily cap), set:
#   ADK_MODEL=deepseek/deepseek-chat   and   DEEPSEEK_API_KEY=...   (plus: pip install litellm)
# Any non-Gemini value is routed through ADK's LiteLlm wrapper (see resolve_model). Gemini values
# pass straight through as ADK's native string path — no litellm needed for the default.
MODEL = os.getenv("ADK_MODEL", "gemini-2.5-flash")


def resolve_model():
    """Return the `model` to hand LlmAgent.

    Gemini model names pass through as a bare string (ADK's native Gemini path — no extra deps).
    Any other provider (e.g. 'deepseek/deepseek-chat', 'openai/gpt-4o') is wrapped in ADK's
    LiteLlm adapter, which needs `pip install litellm` and that provider's API key in the env
    (DeepSeek reads DEEPSEEK_API_KEY). Switch purely via ADK_MODEL; Gemini stays the default.
    """
    if MODEL.startswith("gemini") or MODEL.startswith("models/gemini"):
        return MODEL
    try:
        from google.adk.models.lite_llm import LiteLlm
    except ImportError as e:
        raise RuntimeError(
            f"ADK_MODEL='{MODEL}' is a non-Gemini model, which needs LiteLlm. "
            f"Run: pip install litellm  (and set the provider key, e.g. DEEPSEEK_API_KEY "
            f"for deepseek/* models). Gemini models need none of this."
        ) from e
    return LiteLlm(model=MODEL)


def build_mcp_toolset() -> McpToolset:
    """Spawn the local stdio MCP server as a subprocess and expose its tools to the agent.

    cwd is pinned to the repo root so `python -m mcp_server.server` resolves the package.
    """
    return McpToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command="python3",
                args=["-m", "mcp_server.server"],
                cwd=str(REPO_ROOT),
            ),
        ),
        # Defensive: only ever surface our two curated tools, even if the server grows.
        tool_filter=["get_nap_guidance", "get_milestone_checkin"],
    )


def build_agent() -> LlmAgent:
    """Return the one agent, wired to the local knowledge server.

    No network call happens here — constructing the agent is cheap and key-free. The Gemini
    key is only needed when the agent is actually RUN (the decide/observe loop, arc 3).
    """
    return LlmAgent(
        name="mom_day_organiser",
        model=resolve_model(),
        instruction=SYSTEM_INSTRUCTION,
        tools=[build_mcp_toolset()],
    )


async def list_mcp_tools() -> list[str]:
    """Prove the agent<->MCP seam WITHOUT the model: spawn the server, return its tool names.

    Needs no GOOGLE_API_KEY — this is the MCP handshake only, not a Gemini call. This is the
    arc-2 checkpoint: 'agent lists + calls a tool live.'
    """
    toolset = build_mcp_toolset()
    try:
        tools = await toolset.get_tools()
        return [t.name for t in tools]
    finally:
        await toolset.close()


if __name__ == "__main__":
    import asyncio

    names = asyncio.run(list_mcp_tools())
    print("Agent sees MCP tools:", names)

    agent = build_agent()
    print(f"Built LlmAgent '{agent.name}' on model '{MODEL}' with {len(agent.tools)} toolset(s).")

    if not os.getenv("GOOGLE_API_KEY"):
        print("\nNote: set GOOGLE_API_KEY (see .env.example) to run the model-driven loop — arc 3.")
