"""The ONE agent: an ADK LlmAgent that consumes the local stdio MCP server via McpToolset.

Arc 2 — the wiring. A REAL LlmAgent + a REAL McpToolset pointed at mcp_server/server.py, so
the MODEL (not a hardcoded sequence) decides when to call get_nap_guidance /
get_milestone_checkin. Importing ADK without instantiating it (the NutriGuard mistake) does not
count: build_agent() returns a live agent, and list_mcp_tools() proves the server's two tools
are actually exposed to it.

Two tools, not three — play is generated by the agent from the milestones, not served as a tool
(docs/DECISIONS.md).

Facts discipline lives in the system prompt (agent/instructions.py, OWNED BY SUJATHA — imported
here, never edited here). Personal data never leaves the device: only age_months goes to a tool.

Verified against google-adk 2.3.0 + mcp 1.28.0:
  LlmAgent(name=, model=, instruction=, tools=[McpToolset(...)])
  McpToolset(connection_params=StdioConnectionParams(server_params=StdioServerParameters(...)))
  await toolset.get_tools()  # spawns the server, lists tools — no model call, no API key
"""
import os
from pathlib import Path

from google.adk.agents import LlmAgent
from google.adk.tools.mcp_tool import McpToolset, StdioConnectionParams
from mcp import StdioServerParameters

from dotenv import load_dotenv  # ships with google-adk

from .instructions import SYSTEM_INSTRUCTION

REPO_ROOT = Path(__file__).resolve().parent.parent

# Load .env here (not only in runner.py) so MODEL/backend selection is correct no matter how the
# agent is entered — the `python -m agent.agent` self-check, the web app, or the eval harness.
# Must run BEFORE MODEL is read below.
load_dotenv(REPO_ROOT / ".env")

# Model is env-switchable via ADK_MODEL. Default: gemini-3.5-flash (GA on Vertex as of May 2026;
# chosen over 2.5-flash for more imaginative play-activity generation). Models rotate fast —
# gemini-2.0-flash retired 2026-06-01, gemini-2.5-flash retires 2026-10-16 — so keep this an env
# var, never hardcode a model deeper in. Check live model ids/regions if a call 404s on the model:
# https://docs.cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions
#
# Backends (resolve_model): any non-Gemini value (e.g. deepseek/deepseek-chat) is
# routed through ADK's LiteLlm wrapper and needs that provider's key (DEEPSEEK_API_KEY) + litellm.
# Gemini names pass through as ADK's native string path (AI Studio or
# Vertex, per GOOGLE_GENAI_USE_VERTEXAI); 

MODEL = os.getenv("ADK_MODEL", "gemini-3.5-flash")


def _is_gemini(name: str) -> bool:
    return name.startswith("gemini") or name.startswith("models/gemini")


def _use_vertex() -> bool:
    """True when Gemini calls should route to Vertex AI (Cloud-billed, free-trial-credit-eligible)
    instead of AI Studio. google-genai reads GOOGLE_GENAI_USE_VERTEXAI itself; we mirror it here
    only to validate config and to label the active backend."""
    return os.getenv("GOOGLE_GENAI_USE_VERTEXAI", "").strip().lower() in ("1", "true", "yes")


def active_backend() -> str:
    """One-line label of the backend the current env selects — for the self-check and logs."""
    if not _is_gemini(MODEL):
        return f"{MODEL} (LiteLlm)"
    route = "Vertex AI (ADC · uses Cloud credits)" if _use_vertex() else "AI Studio (GOOGLE_API_KEY)"
    return f"{MODEL} · {route}"


def resolve_model():
    """Return the `model` to hand LlmAgent. Switch backends purely via ENV — no code change:

        DeepSeek          ADK_MODEL=deepseek/deepseek-chat  + DEEPSEEK_API_KEY
        Gemini · AIStudio ADK_MODEL=gemini-2.5-flash        + GOOGLE_API_KEY
        Gemini · Vertex   ADK_MODEL=gemini-2.5-flash        + GOOGLE_GENAI_USE_VERTEXAI=TRUE
                          + GOOGLE_CLOUD_PROJECT + GOOGLE_CLOUD_LOCATION + ADC (no API key)

    Gemini names pass through as a bare string; google-genai picks Vertex vs AI Studio from
    GOOGLE_GENAI_USE_VERTEXAI. Non-Gemini names are wrapped in ADK's LiteLlm adapter (needs
    `pip install litellm` + that provider's key, e.g. DEEPSEEK_API_KEY).
    """
    if _is_gemini(MODEL):
        if _use_vertex():
            missing = [v for v in ("GOOGLE_CLOUD_PROJECT", "GOOGLE_CLOUD_LOCATION")
                       if not os.getenv(v)]
            if missing:
                raise RuntimeError(
                    "Vertex backend selected (GOOGLE_GENAI_USE_VERTEXAI=TRUE) but missing "
                    f"{', '.join(missing)}. Set them (e.g. GOOGLE_CLOUD_LOCATION=us-central1) and "
                    "authenticate ADC: `gcloud auth application-default login` locally, or the "
                    "Cloud Run service account in deployment."
                )
        return MODEL
    try:
        from google.adk.models.lite_llm import LiteLlm
    except ImportError as e:
        raise RuntimeError(
            f"ADK_MODEL='{MODEL}' is a non-Gemini model, which needs LiteLlm. "
            f"Run: pip install litellm  (and set the provider key, e.g. DEEPSEEK_API_KEY "
            f"for deepseek/* models). Gemini models need none of this."
        ) from e
    return LiteLlm(model=MODEL)


def build_mcp_toolset() -> McpToolset:
    """Spawn the local stdio MCP server as a subprocess and expose its tools to the agent.

    cwd is pinned to the repo root so `python -m mcp_server.server` resolves the package.
    """
    return McpToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command="python3",
                args=["-m", "mcp_server.server"],
                cwd=str(REPO_ROOT),
            ),
        ),
        # Defensive: only ever surface our two curated tools, even if the server grows.
        tool_filter=["get_nap_guidance", "get_milestone_checkin"],
    )


def build_agent() -> LlmAgent:
    """Return the one agent, wired to the local knowledge server.

    No network call happens here — constructing the agent is cheap and key-free. The Gemini
    key is only needed when the agent is actually RUN (the decide/observe loop, arc 3).
    """
    return LlmAgent(
        name="mom_day_organiser",
        model=resolve_model(),
        instruction=SYSTEM_INSTRUCTION,
        tools=[build_mcp_toolset()],
    )


async def list_mcp_tools() -> list[str]:
    """Prove the agent<->MCP seam WITHOUT the model: spawn the server, return its tool names.

    Needs no GOOGLE_API_KEY — this is the MCP handshake only, not a Gemini call. This is the
    arc-2 checkpoint: 'agent lists + calls a tool live.'
    """
    toolset = build_mcp_toolset()
    try:
        tools = await toolset.get_tools()
        return [t.name for t in tools]
    finally:
        await toolset.close()


if __name__ == "__main__":
    import asyncio

    names = asyncio.run(list_mcp_tools())
    print("Agent sees MCP tools:", names)

    agent = build_agent()
    print(f"Built LlmAgent '{agent.name}' on backend: {active_backend()} "
          f"— {len(agent.tools)} toolset(s).")

    # Backend-aware credential hint (only the selected backend's key/auth matters).
    if not _is_gemini(MODEL):
        provider = MODEL.split("/", 1)[0].upper()
        if not os.getenv(f"{provider}_API_KEY"):
            print(f"\nNote: set {provider}_API_KEY to run the model-driven loop (see .env.example).")
    elif _use_vertex():
        print("\nNote: Vertex backend — ensure ADC is set "
              "(`gcloud auth application-default login`) to run the loop.")
    elif not os.getenv("GOOGLE_API_KEY"):
        print("\nNote: set GOOGLE_API_KEY (see .env.example) to run the model-driven loop — arc 3.")
